Repository beqom/alto, pull requests merged in 2019-09, with the labels that each got.

#839 Bugfix - Missing styling for selected item in typehead
  src/alto-ui/Form/Typeahead/Typeahead.js
  src/alto-ui/List/List.scss
Labels: bug

#840 Bugfix - Missing styling for selected item in typehead
  src/alto-ui/Form/Typeahead/Typeahead.js
  src/alto-ui/List/List.scss
Labels: bug

#848 0.13 - bugfix ie issue on fields size (#789)
  src/alto-ui/Form/TextField/TextField.js
  src/alto-ui/Form/TextField/TextField.scss
  src/alto-ui/Form/Typeahead/Typeahead.scss
Labels: bug, ie

#851 Release v0.20.17
  package.json
  src/alto-ui/scss/variables.scss
Labels: enhancement, feature

#853 Feature/added outline prop for sidenav
  src/alto-ui/SideNav/SideNav.js
Labels: feature

#854 feature - added possibility to setup outline for sidenav icons
  src/alto-ui/SideNav/SideNav.js
Labels: feature

#852 bugfix/datepicker fixed jumping on select date and fixed not selected…
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#844 bugfix - fixed set value on change date for datepicker in dropdown
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#849 bugfix DatagridRows: display is broken when column groupedby is not visible
  src/alto-ui/Datagrid/Datagrid.js
Labels: bug

#856 release/v0.20.18
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#857 v0.13.31
  package.json
  src/alto-ui/scss/variables.scss
Labels: enhancement

#859 bugfix/BQM-2179 fixed select month, year and time in date picker
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#858 bugfix/BQM-2179 fixed select month, year and time in date picker
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#860 Bugfix - IE11 - Misalignment on last row in Datagrid when column is f…
  src/alto-ui/Datagrid/Datagrid.scss
  src/alto-ui/scss/variables.scss
Labels: bug, ie

#863 Bugfix - fixed displaying value of dropdown list after being selected…
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
Labels: bug

#866 added possibility to empty value for year in datepic…
  src/alto-ui/Form/DatePicker/DatePicker.js
  src/alto-ui/Form/DatePicker/DatePickerHeader.js
Labels: feature

#867 added possibility to empty value for year in datepicker
  src/alto-ui/Form/DatePicker/DatePicker.js
  src/alto-ui/Form/DatePicker/DatePickerHeader.js
Labels: feature

#870 v0.20.20
  package.json
  src/alto-ui/scss/variables.scss
Labels: bug

#871 bugfix typeahead clear icon width
  src/alto-ui/Form/Typeahead/Typeahead.scss
Labels: bug

#864 Bugfix - IE11 - Fixed closing dropdown when user is clicking on scrol…
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
  src/alto-ui/Datagrid/helpers.js
  src/alto-ui/Form/Typeahead/Typeahead.js
  src/alto-ui/Popover/Popover.js
  src/alto-ui/RelativeBox/RelativeBox.js
Labels: bug, ie

#865 Tabs: accept Button and Link
  src/alto-ui/Tabs/Tabs.js
  src/alto-ui/Tabs/Tabs.scss
Labels: bug
