Repository beqom/alto, pull requests merged in 2019-08, with the labels that each got.

#766 Bugfix remove X from ie search input
  src/alto-ui/scss/base.scss
Labels: ie

#769 IE11 : drop down list icon not displayed
  src/alto-ui/Form/TextField/TextField.scss
Labels: ie

#771 IE11 : drop down list icon not displayed
  src/alto-ui/Form/TextField/TextField.scss
Labels: ie

#773 Bump to 0.13.29
  package.json
  src/alto-ui/scss/variables.scss
Labels: DO NOT MERGE

#776 bugfix DatagridGroupedRow: render cell
  src/alto-ui/Datagrid/components/DatagridGroupedRow/DatagridGroupedRow.js
Labels: bug

#779 bugfix DatagridCellInput: onChange function
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
Labels: bug

#783 bugfix/Add missing pagination ids
  src/alto-ui/Pagination/Pagination.js
  src/alto-ui/Pagination/Pagination.scss
Labels: bug

#785 v0.20.10
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#786 bugfix/Fix checkbox and switch on List
  src/alto-ui/List/List.js
Labels: bug

#791 bugfix/Fix pagination on IE
  src/alto-ui/Pagination/Pagination.js
Labels: bug

#789 bugfix ie issue on fields size
  src/alto-ui/Form/TextField/TextField.js
  src/alto-ui/Form/TextField/TextField.scss
  src/alto-ui/Form/Typeahead/Typeahead.scss
Labels: ie

#790 Bugfix - Added bold style to edited typehead item in datagrid cell input
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.scss
  src/alto-ui/Form/Typeahead/Typeahead.js
Labels: bug

#792 Fix toggle button in Side nav
  src/alto-ui/SideNav/SideNav.scss
Labels: bug

#793 bugfix/Change Side Nav links color for light theme
  src/alto-ui/SideNav/SideNav.scss
Labels: bug

#794 feature/Add custom field type to list
  src/alto-ui/List/List.js
Labels: feature

#795 fixed text input
  src/alto-ui/Form/TextField/TextField.js
  src/alto-ui/Form/Typeahead/Typeahead.scss
Labels: bug, ie

#797 release/v0.20.11
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#800 Bugfix Empty list-type cell when editing is disabled
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
Labels: bug

#802 Change of badge colors in order to uniform the look in the list
  src/alto-ui/Badge/Badge.scss
  src/alto-ui/Form/Label/Label.scss
Labels: enhancement

#799 bugfix/datepicker-save-on-blur fixed change date for datepicker on in…
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
Labels: bug

#798 enhancement - remove line height for DatagridCell__content--header
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
Labels: enhancement

#805 bugfix/Update list with media
  src/alto-ui/List/List.scss
Labels: enhancement

#806 release/v0.20.12
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#808 IE 11 - Width of elements in list is not correctly calculated
  src/alto-ui/List/List.scss
Labels: bug, ie

#809 bugfix/Fix typeahead text fields on IE
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
  src/alto-ui/Form/TextField/TextField.scss
  src/alto-ui/Form/Typeahead/Typeahead.scss
Labels: bug

#810 bugfix/Pass default property checked to checkbox to avoid sending null
  src/alto-ui/Form/CheckBox/CheckBox.js
Labels: bug

#812 Bugfix Button: Large props was missing in buttonProps
  src/alto-ui/Button/Button.js
Labels: bug

#813 bugfix ie calculating dropdown width
  src/alto-ui/Dropdown/Dropdown.js
  src/alto-ui/Dropdown/Dropdown.scss
Labels: bug, ie

#807 New pergamen icon
  src/alto-ui/Icons/Pergamen.js
  src/alto-ui/Icons/index.js
Labels: enhancement

#821 bugfix retrieve hide label prop for select drop down
  src/alto-ui/Form/Select/SelectDropdown.js
Labels: bug

#822 bugfix textfield input width
  src/alto-ui/Form/TextField/TextField.scss
Labels: bug

#819 Fix invoke props function in list with badges
  src/alto-ui/List/List.js
Labels: bug

#824 release/v0.20.14
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#825 bugfix/Fix List with badges
  src/alto-ui/List/List.js
Labels: bug

#826 feature/update potential security vulnerabilities
  package.json
  yarn.lock
Labels: enhancement

#827 feature/update-webcomponents-package
  package.json
  yarn.lock
Labels: feature

#828 release/v0.20.15
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#820 enhancement - datagrid - add tooltip in info fields
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
Labels: enhancement

#829 bugfix/Add missing props to list with badges
  src/alto-ui/List/List.js
Labels: bug

#830 feature added onerror and onload service for image component
  src/alto-ui/Image.js
Labels: feature

#831 release/v0.20.16
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#833 bugfix/clear-datapicker-value
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug
