Repository beqom/alto, pull requests merged in 2019-07, with the labels that each got.

#703 bugfix/pagination validation
  src/alto-ui/Pagination/Pagination.js
  src/alto-ui/Pagination/Pagination.scss
Labels: bug

#704 Bugfix - Grouping using ID not name
  src/alto-ui/Datagrid/components/DatagridGroupedRow/DatagridGroupedRow.js
Labels: bug

#727 bugfix Datagrid: disabled checkbox without key
  src/alto-ui/Datagrid/Datagrid.js
Labels: bug

#745 IE 11 - Fixed minimal width calculation
  src/alto-ui/Card/Card.scss
  src/alto-ui/Form/TextField/TextField.scss
Labels: bug

#744 bugfix/infinite loop in relative box
  src/alto-ui/Form/Typeahead/Typeahead.js
  src/alto-ui/RelativeBox/RelativeBox.js
Labels: WIP, bug

#746 bugfix Popover: pass target to RelativeBox
  src/alto-ui/Popover/Popover.js
Labels: bug

#743 IE 11 - Fixed checked state style for Switch
  src/alto-ui/Form/Switch/Switch.scss
Labels: bug

#749 bugfix/fix line height in text field
  src/alto-ui/Form/TextField/TextField.scss
Labels: bug

#750 bugfix/Fix properly dropdown render
  src/alto-ui/RelativeBox/RelativeBox.js
Labels: bug

#752 Checkbox Label Issue on IE
  src/alto-ui/Form/Switch/Switch.scss
Labels: bug

#754 feature/Modify SideNav and add secondary items
  src/alto-ui/SideNav/SideNav.js
  src/alto-ui/SideNav/SideNav.scss
  src/alto-ui/SideNav/story.js
Labels: enhancement

#757 bugfix - ms browsers - set overflow style to scrollbar
  src/alto-ui/Datagrid/Datagrid.scss
Labels: bug

#758 feature/ Bump to v.0.20.4
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature
