Repository beqom/alto, pull requests merged in 2019-06, with the labels that each got.

#661 feature/Pagination redesign
  package.json
  src/alto-ui/Pagination/Pagination.js
  src/alto-ui/Pagination/Pagination.scss
  src/alto-ui/Pagination/__tests__/Pagination.test.js
  src/alto-ui/Pagination/story.js
Labels: enhancement

#663 bugfix - add condition in componentDidUpdate to prevent infinite loop
  src/alto-ui/RelativeBox/RelativeBox.js
Labels: bug

#669 VisuallyHidden: fix top display issue when using checkboxes
  src/alto-ui/scss/placeholders.scss
  yarn.lock
Labels: bug

#662 bugfix DatePicker: handle errors
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: DO NOT MERGE, bug

#664 0.17 - bugfix - add condition in componentDidUpdate to prevent infinite loop
  src/alto-ui/RelativeBox/RelativeBox.js
Labels: DO NOT MERGE, bug

#672 VisuallyHidden: fix top display issue when using checkboxes
  src/alto-ui/scss/placeholders.scss
Labels: bug

#674 VisuallyHidden: fix top display issue when using checkboxes
  src/alto-ui/scss/placeholders.scss
Labels: bug

#668 HTMLBlock - Manage url with and without http
  .storybook/config.js
  src/alto-ui/HTMLBlock/HTMLBlock.js
  src/alto-ui/HTMLBlock/story.js
Labels: bug

#678 bugfix BQM-786 RelativeBox: refactor to fix regression on position
  src/alto-ui/RelativeBox/RelativeBox.js
Labels: bug

#684 HTMLBlock - Manage url with and without http
  .storybook/config.js
  src/alto-ui/HTMLBlock/HTMLBlock.js
  src/alto-ui/HTMLBlock/story.js
Labels: bug

#682 feature/pagination dropdown
  src/alto-ui/Dropdown/Dropdown.js
  src/alto-ui/Pagination/Pagination.js
  src/alto-ui/Pagination/Pagination.scss
  src/alto-ui/Pagination/__tests__/Pagination.test.js
  src/alto-ui/Pagination/story.js
Labels: DO NOT MERGE, feature
