Repository beqom/alto, pull requests merged in 2019-05, with the labels that each got.

#613 Datagrid: fix horizontal missalignment and horizontal scroll
  src/alto-ui/Datagrid/Datagrid.scss
  src/alto-ui/Datagrid/components/DatagridHeaderRow/DatagridHeaderRow.scss
Labels: DO NOT MERGE, bug

#619 bugfix SelectDropdown: Add title
  src/alto-ui/Form/Select/SelectDropdown.js
Labels: bug

#621 bugfix DatePicker: avoid errors when enter a invalid date format
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#630 bugfix DatagridCell: shouldUpdate
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
Labels: bug

#612 Fixed wrong spacing in radio and checkbox labels
  src/alto-ui/Form/CheckBox/CheckBox.scss
  src/alto-ui/Form/Radio/Radio.scss
  src/alto-ui/scss/placeholders.scss
Labels: bug

#636 v0.13 - add cell alignment in datagrid cell
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.js
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
Labels: DO NOT MERGE

#638 bugfix Datagrid: when rows are clickable, avoid checkboxes to be over…
  src/alto-ui/Datagrid/Datagrid.js
  src/alto-ui/Datagrid/components/DatagridRow/DatagridRow.js
Labels: bug

#650 bugfix/Fix default check for checkbox on data grid
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Input/Input.js
Labels: bug

#651 bugfix/Avoid memory leaks on datagrid
  src/alto-ui/Datagrid/Datagrid.js
Labels: bug

#653 bugfix DatePicker: handle errors
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#659 bugfix SideNav: use id for key instead of title
  src/alto-ui/SideNav/SideNav.js
Labels: bug
