Repository beqom/alto, pull requests merged in 2019-10, with the labels that each got.

#875 Bugfix - Active row needs to have white inputs
  src/alto-ui/Datagrid/components/DatagridCell/DatagridCell.scss
Labels: bug

#873 added labels ( translations ) for datepickers
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#874 Bugfix - IE11 - Fixed stucking typeahead dropdown
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/Typeahead/Typeahead.js
Labels: bug

#879 Release v0.21.6
  package.json
  src/alto-ui/scss/variables.scss
Labels: enhancement

#881 Bugfix - Fix typeahead load more
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/Typeahead/Typeahead.js
Labels: bug

#880 bugix Datagrid: Enable checkboxes event if there is no frozen columns
  src/alto-ui/Datagrid/Datagrid.js
Labels: bug

#887 Bugfix/datapicker format date to iso issue
  src/alto-ui/Form/DatePicker/DatePicker.js
Labels: bug

#890 bugfix: List add id on button
  src/alto-ui/List/List.js
Labels: bug

#893 Remove onClose on onBlur
  src/alto-ui/Datagrid/components/DatagridCellInput/DatagridCellInput.js
  src/alto-ui/Form/Typeahead/Typeahead.js
Labels: bug

#896 Filter Not Working when select invisible element on first page
  src/alto-ui/Form/Typeahead/Typeahead.js
Labels: DO NOT MERGE

#900 bump 0.20.22
  package.json
  src/alto-ui/scss/variables.scss
Labels: feature

#895 fixes for lagging scroll on process and fix IE11 performance
  src/alto-ui/Datagrid/Datagrid.js
  src/alto-ui/Datagrid/Datagrid.scss
  src/alto-ui/helpers/__tests__/sum.test.js
  src/alto-ui/helpers/navigator.js
  src/alto-ui/helpers/sum.js
Labels: bug, ie

#901 v0.21.9
  package.json
  src/alto-ui/scss/variables.scss
Labels: bug, feature, ie

#902 Release/0.21/lagging scroll on processes and fix ie11 performance
  src/alto-ui/Datagrid/Datagrid.js
  src/alto-ui/Datagrid/Datagrid.scss
  src/alto-ui/helpers/__tests__/sum.test.js
  src/alto-ui/helpers/navigator.js
  src/alto-ui/helpers/sum.js
Labels: enhancement, ie

#903 fixes for lagging scroll on process and fix IE11 performance
  src/alto-ui/Datagrid/Datagrid.js
  src/alto-ui/Datagrid/Datagrid.scss
  src/alto-ui/helpers/__tests__/sum.test.js
  src/alto-ui/helpers/navigator.js
  src/alto-ui/helpers/sum.js
  src/alto-ui/scss/variables.scss
Labels: enhancement, ie

#904 0.20.23
  package.json
  src/alto-ui/scss/variables.scss
Labels: enhancement, ie

#905 horizontal scroll is not needed for grid if grid is too short
  src/alto-ui/Datagrid/Datagrid.scss
Labels: bug, ie

#907 horizontal scroll is not needed for grid if grid is too short
  src/alto-ui/Datagrid/Datagrid.scss
Labels: bug

#909 v0.20.24
  package.json
  src/alto-ui/scss/variables.scss
Labels: bug

#908 added new icons, added using custom default icon for user avatar
  src/alto-ui/Avatar/Avatar.js
  src/alto-ui/Icons/Department.js
  src/alto-ui/Icons/Payee.js
  src/alto-ui/Icons/Structure.js
  src/alto-ui/Icons/Territory.js
  src/alto-ui/Icons/index.js
Labels: feature
